# roles/kubectl/tasks/main.yml

- name: Download kubectl binary using shell
  shell: |
    curl -L -o /usr/local/bin/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod 755 /usr/local/bin/kubectl
  args:
    warn: false

- name: Verify kubectl installation
  command: kubectl version --client
  register: kubectl_version
  ignore_errors: yes

- name: Display kubectl version
  debug:
    var: kubectl_version.stdout
